# Generated by Django 4.2 on 2023-05-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fifteen_min',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
