# Generated by Django 4.2 on 2023-05-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_account_fifteen_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fifteen_min',
            new_name='fifteen_min_trial',
        ),
        migrations.AddField(
            model_name='account',
            name='profile_updated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
