# Generated by Django 4.2 on 2023-05-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time_to',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
