# Generated by Django 4.2 on 2023-05-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic_app', '0004_alter_ailments_image_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ailments',
            name='image_icon',
            field=models.ImageField(blank=True, null=True, upload_to='picture/'),
        ),
    ]
