# Generated by Django 4.2 on 2023-05-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic_app', '0005_writeus_created_writeus_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
