# Generated by Django 4.2 on 2023-05-26 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medic_app', '0006_appointment_is_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payed', models.BooleanField(default=False)),
                ('payment_IDnumber', models.CharField(blank=True, max_length=70, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('app_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medic_app.appointment')),
            ],
        ),
    ]
